apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::975050222777:role/eksctl-eks1-nodegroup-eks1-ng-priv-NodeInstanceRole-yMkciNJKnoYA
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2025-08-08T06:19:36Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3412"
  uid: e2cabc56-01e6-4b7d-bfdd-01b234379b59
